<a href="https://colab.research.google.com/github/Bandashivamani/23CSBTB39-40/blob/main/array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
list1=[1,3,4]
list2=[2,4,5]
print(list1)
print(list2)
print(type(list1))
print(type(list2))

[1, 3, 4]
[2, 4, 5]
<class 'list'>
<class 'list'>


In [3]:
import numpy as np
array1=np.array(list1)
print(array1)
array2=np.array(list2)
print(array2)


[1 3 4]
[2 4 5]


In [4]:
print(array1+array2)


[3 7 9]


In [5]:
list1_type=type(list1)
list2_type=type(list2)
print(list1_type)
print(list2_type)
array1_type=type(array1)
array2_type=type(array2)
print(array1_type)
print(array2_type)


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
multiplication=array1*array2
print(multiplication)


[ 2 12 20]


In [11]:
division=array1/array2
print(division)

[0.5  0.75 0.8 ]


In [12]:
poweroff=array1**2
print(poweroff)

[ 1  9 16]


In [14]:
sin_result=np.sin(array1)
print("sin result :",sin_result)
log_result=np.log(array1+1)
log2_result=np.log2(array1+1)
print("log result :",log_result)
print("log2 result :",log2_result)
exp_result=np.exp(array1)
print("exp result :",exp_result)

sin result : [ 0.84147098  0.14112001 -0.7568025 ]
log result : [0.69314718 1.38629436 1.60943791]
log2 result : [1.         2.         2.32192809]
exp result : [ 2.71828183 20.08553692 54.59815003]


In [10]:
poweroff=array1**2
print(poweroff)


NameError: name 'poweroff' is not defined

[ 1  9 16]
